*** Variables ***
${CREATE_TABLE_QUERY} =    CREATE TABLE EMPLOYEE (ID INT PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), AGE INT);
${INSERT_QUERY} =    INSERT INTO EMPLOYEE VALUES(5,'Tom','Cruise',55);
${SELECT_ALL_QUERY} =       SELECT * FROM EMPLOYEE;
${UPDATE_QUERY} =    UPDATE EMPLOYEE SET FIRSTNAME = 'Alex' WHERE ID =5;
${DELETE_QUERY} =    DELETE FROM EMPLOYEE WHERE ID=5;